---
# tasks file for ansible-role-mariadb-galera

# Include variables and define needed variables.
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

# Setup/install tasks.
- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

# Configure MariaDB.
- include: config.yml
- include: secure.yml
- include: galera.yml
- include: users.yml

# Configure clustercheck.
- include: clustercheck.yml
  when: galera_clustercheck_enable
